/// Flutter icons Bmi
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Bmi
///      fonts:
///       - asset: fonts/Bmi.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Bmi {
  Bmi._();

  static const _kFontFam = 'Bmi';

  static const IconData female = const IconData(0xe822, fontFamily: _kFontFam);
  static const IconData male = const IconData(0xe823, fontFamily: _kFontFam);
}
